#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package ppan;

class App::ppan : does(Frame);

use utf8;
use v5.40;

use Cwd;
use List::Util 'any';
use Path::Tiny;
use Const::Fast;

class DirIndex : isa(Plack::App::Directory) {

    use Const::Fast;
    use Const::Fast::Exporter;

    const our $dir_page => <<'...';
<!DOCTYPE html>
<html lang="en">
<head>
<title>%s</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link
  rel="stylesheet"
  href="/www/bulma.min.css"
>
<style type='text/css'>
table { width:100%%; }
.name { text-align:left; }
.size, .mtime { text-align:right; }
.type { width:11em; }
.mtime { width:15em; }
</style>
</head>
<body>
<h1>%s</h1>
<hr />
<table>
  <tr>
    <th class='name'>Name</th>
    <th class='size'>Size</th>
    <th class='type'>Type</th>
    <th class='mtime'>Last Modified</th>
  </tr>
%s
</table>
<hr />
</body>
</html>
...

    method BUILDARGS : common (@BUILDARGS) {
        @BUILDARGS;
    }

    ADJUST {
        $Plack::App::Direectory::dir_page = $DirIndex::dir_page;
    };

    $Plack::App::Direectory::dir_page = $dir_page;

    method serve_path : override ($env, $dir) {
        $Plack::App::Direectory::dir_page = $dir_page;
        Plack::App::Directory::serve_path( $self, $env, $dir );
    }
};

const our $DEBUG   => $ENV{DEBUG};
const our $MOUNTRE => qr/^(.+)(?:\:(.+))?$/;

our ( $srvpath, $mount ) = $ARGV[-1] =~ $MOUNTRE;

our $builder = Plack::Builder->new;

sub valid_user ( $user, $pass, $env ) {
    $user eq $ENV{SRV_USER}
      && argon2_verify( $ENV{SRVPATH_PWHASH}, $pass );
}

sub serve_directory ( $path, %args ) {
    ( DirIndex->new( { root => $path } )->to_app, $args{uri} // '/' );
}

sub serve_file ( $file, %args ) {
    (
        Plack::App::File->new( file => $file )->to_app,
        map { s/^([^\/]{1}.+)$/\/$1/r } ( $args{uri} // basename($file) )
    );
}

use Data::Dumper;

sub init ( $path = path( $srvpath // getcwd ), $uri = $mount // undef ) {
    $builder->add_middleware('Debug')
      unless any { $_ } @ENV{qw'NODEBUG PRODUCTION'};
    $builder->app_middleware('REPL') if $ENV{REPLWARNING};

    $builder->add_middleware(
        'Auth::Basic',
        authenticator => sub (@args) {
            valid_user(@args);
        }
    ) unless $ENV{SRVPL_NOLOGIN};

    my ( $app, $mount ) =
        -f $path ? serve_file( $path, uri => $uri )
      : -d $path ? serve_directory( $path, uri => $uri )
      :   die "Path '$path' does not appear to be a file or directory.";

    #dmsg { mount => $mount, app => $app };

    $builder->mount( $mount => $app );
    $builder->mount( '/www' => './www' );
    $builder;
}

unless (caller) {
    require Plack::Runner;

    my $runner = Plack::Runner->new;
    $runner->parse_options( qw(-s Frame::Server), @ARGV );
    $runner->run( init->to_app );

    exit( $? // 0 );
}

method startup {
    ...;
}

init
