#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

package epoch;
class epoch;

use lib 'lib';

use utf8;
use v5.40;

use Getopt::Long;
use Time::HiRes;
use Data::Dumper;

use constant epoch => 
  sub ($fmtstr, $eol = "\n") {
    $eol =~ s/\\(.)?/$1/g;
    warn Dumper({ fmtsrt => $fmtstr, eol => $eol }) if $ENV{DEBUG};
    sprintf( "$fmtstr$eol" // "%d%d$eol"
      , Time::HiRes::gettimeofday )
  };

method $epoch :common {
  epoch->(@_)
}

package main;

use utf8;
use v5.40;

use Data::Dumper;
use GetOpt::Long;

use constant DEBUG => $ENV{EPOCH_DEBUG} // $ENV{EPOCH_DBG} // $ENV{DEBUG};

my $sep    = '.'
my $fmtstr = '%d%d';

if ($$ENV
my $caller = [caller 0];

warn Dumper({ caller => $caller
            , ARGV   => \@ARGV }) if $ENV{DEBUG};

printf epoch::epoch->($ARGV[0] // "%d%d", $ARGV[1] // "\n");
#printf "\n\n"

