#!/usr/bin/env perl
use Object::Pad ':experimental(:all)';

use lib 'lib';

package epoch;

class epoch : isa(Dotfiles::p5);

use utf8;
use v5.40;

use Time::HiRes;
use Const::Fast::Exporter;

use Dotfiles::p5;

const our $DEBUG => $ENV{EPOCH_DEBUG} // $ENV{EPOCH_DBG} // $ENV{DEBUG};

field $delim       = " ";
field $epoch_epoch = [];
field $sep         = '.';
field $fmtstr      = ["%d$sep%d"];
field $eol         = "\n";
field $at          = time;

ADJUSTPARAMS($params) {
    GetOptions(
        'seperator=s'           => \$sep,
        'fmtstr=s'              => $fmtstr,
        'delimiter'             => \$delim,
        'eol=s'                 => \$eol,
        'since|from=s'          => $epoch_epoch,
        'in|at|timw|date|epoch' => $at,
        '<>'                    => sub ($barearg) {
            state $delim_def = shift @$fmtstr;
            push @$fmtstr, $barearg;

            Dotfiles::p5->dmsg(
                {
                    barearg   => $barearg,
                    delim_def => $delim_def,
                    fmgstr    => \@$fmtstr,
                }
            );
        }
    );
}

method $epoch : common {
    epoch->(@_);
}

method epoch ( $fmtstr, $sep = '.', $delim = ' ', $eol = "\n" ) {

}

package main;

use utf8;
use v5.40;

use Getopt::Long qw':config bundling auto_abbrev';

our $tsgen = epoch->new( argv => \@ARGV );
our $cli   = $tsgen->cliopts;

Dotfiles::p5->dmsg(
    {
        caller => [ caller 0 ],
        ARGV   => \@ARGV
    }
);

sub main {
    while ( my ($epoch) = $tsgen->nextts ) {
        $epoch->write;

        #printf epoch::epoch->( $fmtstr // "%d$sep%d", $delim, $eol );
    }
}

main
