#!/usr/bin/env perl

use utf8;
use strict;

use List::AllUtils;
use Path::Tiny;
use Getopt::Long;

my $fin = path($ARGV[0]);
my $pattern = $ARGV[1] =~ /^[a-z0-9_\-]$/ ? ".*$ARGV[1].*" : $ARGV[1]
  // die "No search pattern provided!";

use constant PATTERN => qr/$pattern/i;

foreach my $line (grep { $_ =~ PATTERN } $fin->lines_utf8) {
  
}
#grep

# while (my $line = shift @lines) {
#   say "$1"
# }