#!/usr/bin/env perl

use v5.40;

use Syntax::Keyword::Dynamically;
use IPC::Run3;
use IPC::Nosh::Common;
use Getopt::Long qw(GetOptionsFromArray :config no_ignore_case auto_abbrev);
use Const::Fast;

use JSON::MaybeXS;
use TOML::Tiny qw(to_toml);

use lib 'lib';

const our $fieldmap => { grip => 'Keygrip', fpr => 'Key fingerprint' };

our $cliopt = {
    gpgdir    => $ENV{GPGHOMEDIR},
    separator => ",",
    format    => undef,
    field     => [],
    label     => 1
};

sub gpgfpr ($in) {

    # my $run = run(
    #     [ qw(gpg --verbose --fingerprint), $in ],
    #     out => sub ($line) {
    #         say $line;
    #     },
    #     autochomp => 1
    # );
    #my @fpr;
    my %field =
      map { $_ => [] } grep { defined $$fieldmap{$_} } $$cliopt{field}->@*;
    my @err;

    dynamically $ENV{GNUPGHOME} = $$cliopt{gpgdir};
    run3(
        [ qw(gpg --verbose --with-keygrip --fingerprint), $in ],
        \undef,
        sub ($line) {
            chomp $line;
            foreach my ( $key, $res ) (%field) {
                my $search = $$fieldmap{$key};
                push $res->@*, join "", ( $_ =~ s/(?:$search = |\s)//gr )
                  if $line =~ /^\s*$search/;
            }
        },
        \@err,
    );

    # info "$$fieldmap{$_}:\n"
    #   . join( $$cliopt{separator}, map { "  $_" } $field{$_}->@* ) . "\n"
    #   for keys %field;

    $$cliopt{label} ? \%field : [ values %field ];
}

sub cli ( $argv = \@ARGV ) {
    my @in;
    my %out;

    GetOptionsFromArray(
        $argv, $cliopt,
        'gpgdir|gnupghome=s',
        'field=s@',
        'separator=s',
        'format=s',
        'label!',
        '<>' => sub ($barearg) {
            push @in, $barearg;
        }
    );

    $$cliopt{field}->@* = map { split /,/, $_ } $$cliopt{field}->@*;
    $$cliopt{field} = ['fpr'] unless scalar $$cliopt{field}->@*;

    foreach my $in (@in) {
        $out{$in} = gpgfpr($in);
    }

    # my $backslash = quotemeta '\\';
    # $$cliopt{separator} =~ s!$backslash{1}(.+)!$1!g;
    #say $$cliopt{separator};
    #dmsg $cliopt;

    my $toencode = $$cliopt{label} ? \%out : [ values %out ];
    dmsg $toencode, \%out;

    if ( $$cliopt{format} eq 'json' ) {
        my $json = JSON::MaybeXS->new( utf8 => 1, pretty => 1 );
        say $json->encode($toencode);
    }
    elsif ( $$cliopt{format} eq 'toml' ) {
        say to_toml($toencode);
    }
    else {
        my @out;
        foreach my ( $in, $field ) (%out) {
            push @out,
              (
                $$cliopt{label}
                ? "$in\n  "
                : ""
              )
              . join "\n  ", map {
                (
                    $$cliopt{label}
                    ? "$_="
                    : ""
                  )
                  . join ",", $$field{$_}->@*
              } keys %$field;
        }

        say join "\n", @out;
    }

}

cli( \@ARGV );
dmsg $cliopt

# for gpgid in "$@"; do
#   gpg --verbose --fingerprint $gpgid 2>/dev/null \
#    | head -n2 \
#    | tail -n1 \
#    | perl -Mv5.40 -MIPC::Nosh::IO \
#      -e 'my @fpr; push @fpr, map { chomp $_; join "", $_ =~ s/(?:Key fingerprint = |\s)//gr } (<>); say join " ", @fpr; dmsg(\@fpr)'; done
