#!/usr/bin/env perl

use utf8;
use v5.40;

use lib 'lib';

use Time::HiRes 'gettimeofday';
use Getopt::Long qw(:config no_ignore_case bundling);
use Dotfiles::p5::md2html;

my %opts = (
    filename => 'md2html_' . join ' ', gettimeofday
);

sub run ($opts) {
    my $mdstr;
    if ( $ARGV[0] =~ s/$Dotfiles::p5::md2html::SEPRE// ) {
        if ( my @mdarr = <<>> ) {
            $mdstr = join "\n", map { chomp $_; $_ } (@mdarr);
        }

        #Dotfiles::p5::dmsg({ mdin => $mdin, mdstr => $mdstr });
    }
    
    GetOptions(
        $opts,
        'css|stylesheet|style=s',
        'out|o=s',
        '<>' => sub ($in) {
            say Dotfiles::p5::md2html->md2html($in, %opts)
        }
    )
}

run(\%opts)

