#!/usr/bin/env perl

use utf8;
use v5.40;

use lib 'lib';

use Time::HiRes 'gettimeofday';
use Getopt::Long qw(:config no_ignore_case bundling);
use Dotfiles::p5::md2html;

my %opts = (
    filename => 'md2html_' . join ' ', gettimeofday
);

sub run ($opts) {
    GetOptions(
        $opts,
        'css|stylesheet|style=s',
        'out|o=s',
        '<>' => sub ($in) {
            say Dotfiles::p5::md2html->md2html($in, %opts)
        }
    )
}

run(\%opts)

