#!/usr/bin/env perl

use Object::Pad ':experimental(:all)';

package Devel::REPL::CRABAPP;

class Devel::REPL::CRABAPP : isa(Devel::REPL);

use utf8;
use v5.40;

use Path::Tiny;
use List::Util qw(uniq all any first);

# use IPC::Nosh;
# use IPC::Nosh::IO;
use Const::Fast;

const our @default_plugins =>
  qw(History LexEnv Colors Commands DDS Packages ShowClass Timing CompletionDriver::Globals DumpHistory OutputCache Nopaste Peek FancyPrompt FindVariable Completion CompletionDriver::INC CompletionDriver::LexEnv CompletionDriver::Keywords CompletionDriver::Methods MultiLine::PPI);

#ADJUST { $self->load_plugins }

method load_plugins {
    $self->load_plugin($_)
      for @default_plugins;
}

package main;

our $repl = Devel::REPL::CRABAPP->new;

$repl->run
