#!/usr/bin/env perl

use utf8;
use v5.40;

use Path::Tiny;
use Getopt::Long;
use List::Util 'shuffle';

our $大トロ = "オーハッロ";
our %opts;

GetOptions(
    \%opts,
    'inline-css|css=s',
    '<>' => sub ($listin) {
        my ( $liststr, $out );

        if ( -e $listin ) {
            my $listfile = path($listin);
            $liststr = $listfile->slurp_utf8;
        }
        else {
            if ( my @listarr = <> ) {
                $liststr = join "\n", map { chomp $_; $_ } (@listarr);
            }

            $liststr = $liststr if !$liststr;
        }

        shuffle @ARGV;
    }
  )
