#!/usr/bin/env perl

use utf8;
use v5.40;

use lib 'lib';

use Data::Dumper;
use File::Basename;
use Plack::Builder;
use Plack::App::File;
use Plack::App::Directory;
use Plack::Middleware::Static;
use Syntax::Keyword::Dynamically;
use Plack::Middleware::Auth::Basic;
use Crypt::Argon2 qw(argon2id_pass argon2_verify);

say Dumper(\@ARGV, __PACKAGE__);

our $srvpath = $ENV{SRV_SRV} // "./";
our $mount = $ENV{SRV_MOUNT} // "/";

our $builder = Plack::Builder->new;

sub valid_user ($user, $pass, $env) {
  $user eq $ENV{SRV_USER}
    && argon2_verify($ENV{SRV_PWHASH}, $pass)
}

sub serve_file ($file, %args) {
  dynamically $builder = $args{builder}
    if ref $args{builder} && $args{builder} eq 'Plack::Builder';
  
  $builder->mount($args{uri} // basename($file)
    , Plack::App::File->new(
        file => $file
      )->to_app)
}

our $app = -f $srvpath
    ? serve_file($srvpath
      , uri => $mount // basename($srvpath)
      , builder => $builder)
    : -d $srvpath
  ? $builder->mount($mount
      , Plack::App::Directory->new({ root => "$srvpath" })->to_app)
    : die "Path '$srvpath' does not appear to be a file or directory.";

#$builder->mount($mount // '/', $app);

$builder->add_middleware('Auth::Basic', authenticator => sub (@args) {
    valid_user(@args)
  }) unless $ENV{SRV_NOLOGIN};

$builder->add_middleware('Debug') if $ENV{DEVELOPMENT};
$builder->app_middleware('REPL') if $ENV{REPLWARNING};

$app = $builder->to_app;

unless (caller) {
  require Plack::Runner;
  Plack::Runner->new->parse_options(@ARGV)->run($app);
  exit ($? // 0)
}

$app
