#!/usr/bin/env bash
set -x

openssl req -x509 -out "${outfbase:=localhost}.pem" -keyout \
  "${outfbase}-key.pem" -days "${days:-90}" -newkey "${keyparams:-rsa:2048}" \
  -nodes "${digest--sha256}" -subj "/CN=${cert_cn:-localhost DoH server} \
/O=dnscrypt-proxy/OU=DoH/" -extensions EXT -config <(printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=%s\n\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth" \
    "${san:-"DNS:localhost,IP.0:127.0.0.1,IP.1:::1"}")

status=$?
exit $status
