#!/usr/bin/env perl

package writein;

use utf8;
use v5.40;

use Path::Tiny;
use Data::Dumper;
use Syntax::Keyword::Defer;
use Getopt::Long qw(GetOptionsFromArray :config no_ignore_case auto_abbrev);

my %cliopts = (

    #output => { file => 'writein-isfile-' . time . '.txt' },
    outfile => './writein-' . time . '.txt',
    pathas  => ['absolute']
);

GetOptions(
    \%cliopts,    #' writethrough | write -contents = s{,}',,
    'pathas|normalize-paths|path-as=s{1,}', # method called on Path::Tiny object
                                            #'output=s%',
    'outfile|output=s',
    'uniq!'
);

#my $outpath = path( values $cliopts{outfile}->%* );
my %cksum   = ();
my $outpath = path( $cliopts{outfile} );
my $pathas  = $cliopts{pathas};

my $chain = join "\t->\n", @$pathas;

foreach my $in (@ARGV) {
    $in = path($in);
    my $inabbrev = join "/", map { s/(.{10,})/$1.../r } split /[\/]+/, "$in";

    say STDERR "$inabbrev->$chain >> $outpath";

    for my $method (@$pathas) {
        state $prev;

        if ( $cliopts{uniq} ) {
            my $digest = $in->digest;
            $cksum{$digest} //= [];
            push $cksum{$digest}->@*, $in;
        }

        state $res = $in->$method;

        defer { $prev = $res; $res = undef }

        $in = $res isa 'Path::Tiny' ? $res : $in;
    }

    $outpath->append_utf8("$in\n");
}

say STDERR "▶ Lines Processed: " . scalar @ARGV;
